import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

const colors = ['#1E3A8A', '#2563EB', '#F59E0B', '#D97706', '#64748B', '#0F172A'];
function dateLabel(value) { return new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }); }

export function RevenueTrendChart({ data = [] }) { return <ResponsiveContainer width="100%" height={280}><LineChart data={data}><CartesianGrid strokeDasharray="3 3" stroke="#E2E8F0" /><XAxis dataKey="date" tickFormatter={dateLabel} stroke="#94A3B8" /><YAxis stroke="#94A3B8" /><Tooltip labelFormatter={(value) => new Date(value).toLocaleDateString()} /><Line type="monotone" dataKey="gmv" name="GMV" stroke="#2563EB" strokeWidth={3} dot={false} /><Line type="monotone" dataKey="commission" name="Commission" stroke="#F59E0B" strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer>; }
export function MerchantTrendChart({ data = [] }) { return <ResponsiveContainer width="100%" height={280}><LineChart data={data}><CartesianGrid strokeDasharray="3 3" stroke="#E2E8F0" /><XAxis dataKey="date" tickFormatter={dateLabel} stroke="#94A3B8" /><YAxis stroke="#94A3B8" /><Tooltip labelFormatter={(value) => new Date(value).toLocaleDateString()} /><Line type="monotone" dataKey="revenue" name="Revenue" stroke="#1E3A8A" strokeWidth={3} dot={false} /><Line type="monotone" dataKey="orders" name="Orders" stroke="#F59E0B" strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer>; }
export function GrowthChart({ data = [] }) { return <ResponsiveContainer width="100%" height={260}><BarChart data={data}><CartesianGrid strokeDasharray="3 3" stroke="#E2E8F0" /><XAxis dataKey="date" tickFormatter={dateLabel} stroke="#94A3B8" /><YAxis allowDecimals={false} stroke="#94A3B8" /><Tooltip labelFormatter={(value) => new Date(value).toLocaleDateString()} /><Bar dataKey="signups" name="New merchants" fill="#2563EB" radius={[6, 6, 0, 0]} /><Bar dataKey="suspended" name="Suspended" fill="#F59E0B" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer>; }
export function DistributionChart({ data = [] }) { return <ResponsiveContainer width="100%" height={260}><PieChart><Pie data={data} dataKey="count" nameKey="method" innerRadius={65} outerRadius={95} paddingAngle={3}>{data.map((entry, index) => <Cell key={entry.method} fill={colors[index % colors.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer>; }
export function HorizontalBars({ data = [], dataKey, nameKey }) { return <ResponsiveContainer width="100%" height={Math.max(220, data.length * 48)}><BarChart data={data} layout="vertical" margin={{ left: 20, right: 20 }}><CartesianGrid strokeDasharray="3 3" stroke="#E2E8F0" /><XAxis type="number" stroke="#94A3B8" /><YAxis type="category" dataKey={nameKey} width={100} stroke="#94A3B8" /><Tooltip /><Bar dataKey={dataKey} fill="#2563EB" radius={[0, 6, 6, 0]} /></BarChart></ResponsiveContainer>; }