import { BarChart3, Globe2, Save } from 'lucide-react';
import { useState } from 'react';
import { apiCall } from '../lib/session';

export default function MerchantAnalyticsSettings() {
  const [form, setForm] = useState({ customDomain: '', metaPixelId: '', tiktokPixelId: '', googleAnalyticsId: '' });
  const [state, setState] = useState('');
  function update(key, value) { setForm((current) => ({ ...current, [key]: value })); }
  async function submit(event) { event.preventDefault(); setState('Saving...'); try { await apiCall('put', '/merchants/store', form); setState('Settings saved'); } catch (error) { setState(error.response?.data?.message || 'Unable to save settings'); } }
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top,_rgba(16,185,129,0.14),_transparent_28%),#f6f8f6] px-5 py-8 text-slate-900 sm:px-8"><div className="mx-auto max-w-3xl"><header className="mb-8"><p className="text-[10px] font-black uppercase tracking-[0.22em] text-emerald-700">Store growth</p><h1 className="mt-2 text-4xl font-black tracking-tight">Analytics and domain</h1><p className="mt-3 text-slate-600">Connect your storefront to the tools you already use to understand demand.</p></header><form onSubmit={submit} className="rounded-[1.8rem] border border-slate-200 bg-white p-6 shadow-[0_20px_60px_rgba(15,23,42,0.06)] sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Custom domain<div className="mt-2 flex items-center gap-2 rounded-xl border border-slate-200 px-3"><Globe2 size={17} className="text-emerald-600" /><input value={form.customDomain} onChange={(event) => update('customDomain', event.target.value)} placeholder="shop.example.com" className="w-full py-3 outline-none" /></div></label><label className="text-sm font-bold">Meta Pixel ID<input value={form.metaPixelId} onChange={(event) => update('metaPixelId', event.target.value)} placeholder="123456789" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 outline-none focus:border-emerald-500" /></label><label className="text-sm font-bold">TikTok Pixel ID<input value={form.tiktokPixelId} onChange={(event) => update('tiktokPixelId', event.target.value)} placeholder="CXXXXXXXX" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 outline-none focus:border-emerald-500" /></label><label className="text-sm font-bold">Google Analytics ID<input value={form.googleAnalyticsId} onChange={(event) => update('googleAnalyticsId', event.target.value)} placeholder="G-XXXXXXXXXX" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 outline-none focus:border-emerald-500" /></label></div><div className="mt-8 flex items-center justify-between gap-4"><p className="flex items-center gap-2 text-sm text-slate-500"><BarChart3 size={17} /> Pro and Enterprise features</p><button className="flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-sm font-black text-white"><Save size={16} /> Save settings</button></div>{state && <p className="mt-4 text-sm font-bold text-emerald-700">{state}</p>}</form></div></main>;
}