import { ArrowRight, BarChart3, Check, ChevronDown, Clock3, Menu, MessageCircle, Package, Play, Quote, ShieldCheck, Sparkles, Store, Users, Wallet, X } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import ThemeToggle from './ThemeToggle.jsx';
import LinkPayLogo from './LinkPayLogo.jsx';

const features = [
  { icon: Store, title: 'A storefront in one link', text: 'Give customers one beautiful place to discover your products, story, and checkout.' },
  { icon: MessageCircle, title: 'Social commerce, simplified', text: 'Turn conversations from WhatsApp and social channels into confident orders.' },
  { icon: BarChart3, title: 'Know what is moving', text: 'See sales, views, orders, and conversion signals without the spreadsheet fog.' },
  { icon: Wallet, title: 'Payments that arrive', text: 'Accept trusted local payments and keep every transaction in one calm workspace.' }
];

const steps = [
  ['01', 'Create your signal', 'Set up your store identity, add products, and choose a visual theme that feels like you.'],
  ['02', 'Share the link', 'Put your storefront in your bio, your chats, and every conversation that matters.'],
  ['03', 'Keep the momentum', 'Track orders, understand demand, and give your customers a smoother way to return.']
];

function Logo() {
  return <Link to="/" className="premium-logo"><LinkPayLogo className="linkpay-logo" eager /></Link>;
}

function ProductWindow() {
  return <div className="premium-window animate-float"><div className="premium-window-inner"><div className="premium-window-top"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#ff8c78]" /><span className="h-2 w-2 rounded-full bg-[#c7f36b]" /><span className="h-2 w-2 rounded-full bg-[#a88cff]" /></div><span className="text-[10px] font-bold uppercase tracking-[.18em] text-white/50">LinkPay OS</span></div><div className="premium-window-body"><aside className="premium-window-sidebar space-y-3"><div className="h-7 rounded-lg bg-[#8062f5]" /><div className="h-2 rounded-full bg-white/10" /><div className="h-2 rounded-full bg-white/10" /><div className="h-2 rounded-full bg-white/10" /><div className="mt-10 h-2 rounded-full bg-white/10" /></aside><div className="premium-window-main"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#b9a8ff]">Good morning, Ama</p><h3 className="mt-2 text-xl font-bold text-white">Your store is in motion.</h3></div><div className="rounded-full bg-[#c7f36b] px-2 py-1 text-[9px] font-black text-[#171035]">LIVE</div></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="premium-stat"><p className="text-[9px] text-white/50">Revenue this month</p><p className="mt-2 text-xl font-bold text-white">GH₵ 24,680</p><p className="mt-1 text-[9px] text-[#c7f36b]">+18.4% this week</p></div><div className="premium-stat"><p className="text-[9px] text-white/50">Store visits</p><p className="mt-2 text-xl font-bold text-white">8,412</p><p className="mt-1 text-[9px] text-[#b9a8ff]">Your link is moving</p></div></div><div className="mt-4 rounded-[13px] border border-white/10 bg-white/[.06] p-3"><div className="flex items-center justify-between"><p className="text-[10px] font-bold text-white/70">Sales activity</p><span className="text-[9px] text-white/40">Last 7 days</span></div><div className="mt-5 flex h-20 items-end gap-2">{[32, 48, 40, 68, 56, 82, 72, 94, 78, 100].map((height, index) => <div key={index} className="flex-1 rounded-t bg-gradient-to-t from-[#6d42f5] to-[#b9a8ff]" style={{ height: `${height}%` }} />)}</div></div></div></div></div></div>;
}

export default function PremiumLanding() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <main className="premium-landing">
    <nav className="premium-nav"><div className="premium-container flex h-[76px] items-center justify-between"><Logo /><div className="premium-nav-links flex items-center gap-8"><a href="#features" className="premium-link">Features</a><a href="#how-it-works" className="premium-link">How it works</a><a href="#results" className="premium-link">Results</a><Link to="/marketplace" className="premium-link">Marketplace</Link></div><div className="flex items-center gap-3"><ThemeToggle compact /><Link to="/login" className="premium-link premium-nav-cta px-2">Sign in</Link><Link to="/signup" className="premium-primary premium-nav-cta px-5 py-2.5">Start selling <ArrowRight size={15} /></Link><button type="button" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)} className="premium-mobile-menu rounded-full p-2 text-[#0b0820]">{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></div></div>{menuOpen && <div className="premium-container flex flex-col gap-4 border-t border-black/5 py-5 md:hidden"><a href="#features" onClick={() => setMenuOpen(false)} className="premium-link">Features</a><a href="#how-it-works" onClick={() => setMenuOpen(false)} className="premium-link">How it works</a><a href="#results" onClick={() => setMenuOpen(false)} className="premium-link">Results</a><Link to="/login" className="premium-link">Sign in</Link><Link to="/signup" className="premium-primary w-full">Start selling <ArrowRight size={15} /></Link></div>}</nav>

    <section className="premium-hero"><div className="premium-container relative grid min-h-[680px] items-center gap-14 py-20 lg:grid-cols-[.9fr_1.1fr] lg:py-28"><div className="relative z-10"><span className="premium-pill"><Sparkles size={13} /> The operating system for social commerce</span><h1 className="premium-heading mt-7 max-w-2xl">Turn every link into a <span>storefront.</span></h1><p className="premium-body mt-7 max-w-xl">LinkPay gives Ghanaian merchants a fast store, social checkout, payments, and daily operations in one focused workspace.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/signup" className="premium-primary">Create your store <ArrowRight size={17} /></Link><a href="#showcase" className="premium-secondary"><Play size={15} fill="currentColor" /> See how it works</a></div><div className="mt-10 flex flex-wrap items-center gap-6 text-sm font-semibold text-[#6b6878]"><span className="flex items-center gap-2"><ShieldCheck size={17} className="text-[#6d42f5]" /> Secure by default</span><span className="flex items-center gap-2"><Clock3 size={17} className="text-[#6d42f5]" /> Live in minutes</span></div></div><div className="relative z-10"><ProductWindow /><div className="absolute -bottom-5 -left-5 hidden rounded-2xl border border-white/70 bg-white/80 p-4 shadow-xl backdrop-blur-md sm:block"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#eee9ff] text-[#6d42f5]"><Package size={17} /></div><div><p className="text-[10px] font-bold text-[#6b6878]">New order</p><p className="text-xs font-black text-[#0b0820]">Classic Tee · GH₵ 280</p></div></div></div></div></div></section>

    <section className="border-b border-[#ebe8f2] bg-white"><div className="premium-container flex flex-col items-center justify-between gap-5 py-8 text-center sm:flex-row sm:text-left"><p className="text-sm font-semibold text-[#6b6878]">Built for the way modern merchants grow.</p><div className="flex flex-wrap justify-center gap-x-8 gap-y-3 text-sm font-black tracking-tight text-[#b0adba]"><span>SHOPIFY-READY</span><span>PAYSTACK</span><span>WHATSAPP</span><span>GHANA MADE</span></div></div></section>

    <section id="features" className="bg-white py-24 sm:py-32"><div className="premium-container"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[.22em] text-[#7452ef]">Everything in one signal</p><h2 className="mt-5 text-4xl font-black tracking-[-.06em] text-[#0b0820] sm:text-5xl">The simple advantage of having your commerce in one place.</h2><p className="premium-body mt-5 max-w-xl">Less switching. More clarity. A customer experience that feels considered from the first tap to the last confirmation.</p></div><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{features.map(({ icon: Icon, title, text }) => <article key={title} className="premium-feature-card"><div className="premium-icon"><Icon size={20} /></div><h3 className="mt-7 text-lg font-black text-[#0b0820]">{title}</h3><p className="mt-3 text-sm leading-7 text-[#6b6878]">{text}</p><ArrowRight size={17} className="mt-7 text-[#7452ef]" /></article>)}</div></div></section>

    <section id="showcase" className="premium-section-dark py-24 sm:py-32"><div className="premium-container grid items-center gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#b9a8ff]">Designed for momentum</p><h2 className="mt-5 text-4xl font-black tracking-[-.06em] sm:text-5xl">Your store should feel like your best salesperson.</h2><p className="mt-6 max-w-md text-lg leading-8 text-white/60">A storefront, a point of sale, an analytics pulse, and a social engine that all speak the same language.</p><div className="mt-8 space-y-4 text-sm font-semibold text-white/80"><p className="flex items-center gap-3"><Check size={17} className="text-[#c7f36b]" /> Beautiful on every screen</p><p className="flex items-center gap-3"><Check size={17} className="text-[#c7f36b]" /> Checkout built for local payments</p><p className="flex items-center gap-3"><Check size={17} className="text-[#c7f36b]" /> Signals that help you decide</p></div></div><div className="glass-panel rounded-[24px] p-3"><div className="overflow-hidden rounded-[18px] bg-[#f8f7fc] p-6 sm:p-9"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#7452ef]">Your storefront</p><h3 className="mt-2 text-3xl font-black tracking-tight text-[#0b0820]">Mile Market.</h3></div><div className="rounded-full bg-[#eee9ff] px-3 py-1 text-[10px] font-black text-[#6d42f5]">Open now</div></div><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="col-span-2 rounded-2xl bg-gradient-to-br from-[#dcd1ff] to-[#8d68ff] p-5 sm:col-span-2"><p className="text-xs font-black text-[#271758]">The latest drop</p><p className="mt-12 text-2xl font-black text-[#171035]">Made to be passed along.</p></div><div className="hidden rounded-2xl bg-[#0b0820] p-5 sm:block"><Users className="text-[#c7f36b]" size={20} /><p className="mt-12 text-sm font-black text-white">2.4k people reached</p></div></div><div className="mt-3 grid grid-cols-3 gap-3">{['New arrivals', 'Best sellers', 'For your home'].map((label) => <div key={label} className="rounded-xl border border-[#e7e2f1] bg-white p-3 text-center text-[10px] font-black text-[#6b6878]">{label}</div>)}</div></div></div></div></section>

    <section id="how-it-works" className="bg-[#f8f7fc] py-24 sm:py-32"><div className="premium-container"><div className="text-center"><p className="text-xs font-black uppercase tracking-[.22em] text-[#7452ef]">Three steps to lift-off</p><h2 className="mt-5 text-4xl font-black tracking-[-.06em] text-[#0b0820] sm:text-5xl">From idea to order, without the noise.</h2></div><div className="mt-14 grid gap-5 lg:grid-cols-3">{steps.map(([number, title, text]) => <article key={number} className="relative rounded-[20px] border border-[#e8e3f0] bg-white p-7"><span className="text-sm font-black text-[#9b7cff]">{number}</span><h3 className="mt-16 text-xl font-black text-[#0b0820]">{title}</h3><p className="mt-3 text-sm leading-7 text-[#6b6878]">{text}</p><div className="absolute right-7 top-7 h-2 w-2 rounded-full bg-[#8d68ff] shadow-[0_0_0_7px_#eee9ff]" /></article>)}</div></div></section>

    <section id="results" className="premium-section-purple py-24 sm:py-32"><div className="premium-container"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#d9ceff]">A better daily rhythm</p><h2 className="mt-5 text-4xl font-black tracking-[-.06em] sm:text-5xl">More time making. Less time managing.</h2></div><p className="max-w-xl text-lg leading-8 text-white/70">LinkPay is made for people building something real: the boutique owner, the food brand, the creator with a drop, the merchant growing one conversation at a time.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3"><div className="premium-quote md:col-span-2"><Quote size={25} className="text-[#c7f36b]" /><p className="mt-6 max-w-2xl text-2xl font-black leading-tight">“It feels like the first time my online store actually sounds like my brand.”</p><div className="mt-8 flex items-center gap-3 text-sm text-white/60"><div className="grid h-9 w-9 place-items-center rounded-full bg-white/20 font-black text-white">AN</div>Ama N. · Accra, Ghana</div></div><div className="rounded-[20px] bg-[#0b0820] p-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#b9a8ff]">One clear view</p><p className="mt-7 text-5xl font-black">18.4%</p><p className="mt-2 text-sm text-white/55">average weekly lift across your store signals</p></div></div></div></section>

    <section className="bg-white py-24 sm:py-32"><div className="premium-container overflow-hidden rounded-[28px] bg-[#0b0820] px-7 py-14 text-center sm:px-14"><div className="mx-auto max-w-2xl"><p className="text-xs font-black uppercase tracking-[.22em] text-[#b9a8ff]">Your next chapter starts here</p><h2 className="mt-5 text-4xl font-black tracking-[-.06em] text-white sm:text-5xl">Make your next link count.</h2><p className="mt-5 text-lg leading-8 text-white/60">Create a storefront that gives your work the room it deserves.</p><Link to="/signup" className="premium-primary mt-8 bg-white text-[#0b0820] hover:bg-[#c7f36b]">Create your store <ArrowRight size={17} /></Link></div></div></section>

    <footer className="border-t border-[#ebe8f2] bg-white"><div className="premium-container flex flex-col gap-5 py-8 text-sm text-[#6b6878] sm:flex-row sm:items-center sm:justify-between"><Logo /><div className="flex flex-wrap gap-5"><Link to="/login" className="premium-link">Sign in</Link><Link to="/signup" className="premium-link">Create account</Link><Link to="/marketplace" className="premium-link">Marketplace</Link></div><span>© 2026 LinkPay</span></div></footer>
  </main>;
}
