import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { apiClient, formatGHS } from '@my-app/shared';

function injectTracking(merchant) {
  const nodes = [];
  if (merchant?.metaPixelId) { const script = document.createElement('script'); script.dataset.lumaTracking = 'meta'; script.text = `!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');fbq('init','${merchant.metaPixelId}');fbq('track','PageView');`; document.head.appendChild(script); nodes.push(script); }
  if (merchant?.googleAnalyticsId) { const script = document.createElement('script'); script.dataset.lumaTracking = 'google'; script.async = true; script.src = `https://www.googletagmanager.com/gtag/js?id=${encodeURIComponent(merchant.googleAnalyticsId)}`; document.head.appendChild(script); const inline = document.createElement('script'); inline.dataset.lumaTracking = 'google-inline'; inline.text = `window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','${merchant.googleAnalyticsId}')`; document.head.appendChild(inline); nodes.push(script, inline); }
  return () => nodes.forEach((node) => node.remove());
}

export default function StoreFront() {
  const { storeSlug } = useParams(); const [merchant, setMerchant] = useState(null); const [products, setProducts] = useState([]);
  useEffect(() => { let cleanup = () => {}; Promise.all([apiClient.get(`/merchants/public/${storeSlug}`), apiClient.get(`/products/store/${storeSlug}`)]).then(([merchantResponse, productsResponse]) => { setMerchant(merchantResponse.data.merchant); setProducts(productsResponse.data); cleanup = injectTracking(merchantResponse.data.merchant); }).catch(() => {}); return () => cleanup(); }, [storeSlug]);
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top,_rgba(16,185,129,0.14),_transparent_30%),#f6f8f6] px-5 py-8 text-slate-900 sm:px-8"><div className="mx-auto max-w-6xl"><header className="flex items-center justify-between border-b border-slate-200 pb-6"><div><p className="text-[10px] font-black uppercase tracking-[0.22em] text-emerald-700">Verified storefront</p><h1 className="mt-2 text-2xl font-black">{merchant?.storeName || merchant?.businessName || 'Store'}</h1></div><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700">{merchant?.status === 'active' || merchant?.isVerified ? 'Open now' : 'Independent store'}</span></header><section className="py-14"><h2 className="max-w-2xl text-5xl font-black tracking-[-0.05em]">Products worth passing along.</h2><p className="mt-4 max-w-xl text-lg leading-8 text-slate-600">{merchant?.description || 'A considered collection, ready for quick checkout.'}</p><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((product) => <article key={product._id} className="overflow-hidden rounded-[1.5rem] border border-slate-200 bg-white shadow-[0_18px_50px_rgba(15,23,42,0.05)]"><img src={product.imageUrl} alt={product.title} className="h-60 w-full object-cover" /><div className="p-5"><h3 className="font-black">{product.title}</h3><p className="mt-2 text-sm text-slate-500">{product.description}</p><div className="mt-5 flex items-center justify-between"><span className="font-black text-emerald-700">{formatGHS(product.price)}</span><Link to={`/store/${storeSlug}/checkout/${product._id}`} className="rounded-xl bg-slate-900 px-3 py-2 text-xs font-black text-white">Buy now</Link></div></div></article>)}</div></section></div></main>;
}